JSON error response
Turns error messages from:
   Error: ... API error '{"code":400,"message":"Clarification text is empty"}' (invalid statuscode received: 400)
to:
   Error: ... Clarification text is empty (error code 400)

We still need to improve the first part of the error message and error chaining, but at least now you see the actual error message sent back from the server.